value = input('Digite a value: ')
print('Type of {} is {} '.format(value, type(value)))
print('is lower',value.islower())
print('is decimal', value.isdecimal())
print('is numeric',value.isnumeric())
print('is alphabet numeric ', value.isalnum())
print('is alphabet', value.isalpha())
print('is ascii', value.isascii())
print('is digit', value.isdigit())
print('is title', value.istitle())
print('is uppercase', value.isupper())
print('is identifier',value.isidentifier())
print('is space', value.isspace())